leftnav:
- identifier: 82f886fb-be3e-4360-bd44-26efe4ba30ac
  name: Update Log
  pageRef: /pages/update-log
  weight: 10
- identifier: ea6634c6-1841-f34c-97bd-e95620a88401
  name: Instructor Insights
  pageRef: /pages/instructor-insights
  weight: 20
- identifier: f803f749-08f1-c66f-60a3-cce1b7107d8d
  name: Privacy and Surveillance
  pageRef: /pages/privacy-surveillance/
  weight: 30
- identifier: 8918d065-a83d-28bb-930c-c997c41daa24
  name: Inequality, Justice, & Human Rights
  pageRef: /pages/inequality-justice-human-rights
  weight: 40
- identifier: 17e1fff5-e25b-6a04-922e-1cd9935bbd5a
  name: AI and Algorithms
  pageRef: /pages/ai-algorithms/
  weight: 50
- identifier: c511e1f7-485e-7684-30b2-054190e10b7d
  name: Social and Environmental Impacts
  pageRef: /pages/social-environmental-impact
  weight: 60
- identifier: 2d1143ae-8e51-5eea-e1eb-0775e682c7f8
  name: Autonomous Systems and Robotics
  pageRef: /pages/autonomous-systems-and-robotics
  weight: 70
- identifier: a309ad69-914b-c4cb-9139-3610c7e186a1
  name: Ethical Computing and Practice
  pageRef: /pages/ethical-computing-and-practice/
  weight: 80
- identifier: d3d17eb1-05db-0d7b-d44a-25f575d31c08
  name: Law and Policy
  pageRef: /pages/law-policy
  weight: 90
